version: "3.8"

services:
  backend:
    image: nakshatra10/backend:latest
    build:
      context: .
      dockerfile: MoviesAPI/Dockerfile
    environment:
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CLUSTER=${MONGO_CLUSTER}
    ports:
      - "8081:8081"

  frontend:
    image: nakshatra10/frontend:latest
    build:
      context: frontend
    ports:
      - "3000:3000"
