version: "3.7"

services:
  backend:
    image: backend:latest
    build:
      context: ./MoviesAPI
    env_file:
      - .env
    ports:
      - "8080:8080"

  frontend:
    image: frontend:latest
    build:
      context: ./frontend
    ports:
      - "3000:3000"
